### ISSUE TITLE
about model

### ISSUE THREAD

**Issue by mdipierro** [CoursePlanner183/courseplanner#2]
a course should reference a school, like a student does.

optionally the "course_taken" relation between a student and a course may be more completed like:
- applied
- enrolled
- withdrawn
- competed/passed
- completed/failed
-etc.

**Comment by ColbyFrey** [comment]
We've expanded the course_taken tab le to have more data. The relation between the school and course tables is ongoing and I will update as we improve the application.
![image](https://github.com/CoursePlanner183/courseplanner/assets/55164236/ff318248-2aa5-426c-89cb-51d7d0440f93)
